### ISSUE TITLE
Käsittelyerätoiminto: Niteiden lisääminen käsittelylistalle Odotuslista-sivulta ei toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha-23x#135]
### Mikä vikana?

Jos ollaan ymmärretty oikein, odotuslistalle viedyt niteet pitäisi pystyä siirtämään käsittelyerään (käsittelylistalle) Odotuslista-sivulla toiminnolla _+Lisää viimeiset xx nidettä käsittelylistalle_, heti sen jälkeen, kun niteet oli lisätty odotuslistalle. Ohjelma antaa kuitenkin alla näkyvän tiedon, eikä niteet siirry käsittelyerään.
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/9e10447c-7868-4e7d-bd35-19c8e04fcacd)

Niteet saa siirrettyä käsittelyerään kyllä yksitellen, kun avaa luodun käsittelyerän ja lisää siellä niteet toiminnolla _+Lisää niteitä._

Tai voi olla, että olen ymmärtänyt tai tehnyt joitain väärin. :D

### Kuinka toistaa ongelma/asia

1. Luo käsittelyerä, johon haluat niteet lähettää.
2. Lisää lähetettävät niteet ensin odotuslistalle Odotuslista-sivun toiminnolla +Lisää odotuslistalle.
3. Kun niteet on lisätty odotuslistalle, ohjelma ehdottaa: +Lisää viimeiset xx nidettä käsittelylistalle.
4. Valitse käsittelyerä, johon haluat niteet lisätä.
5. Nimeke- ja Tekijä-kenttiin tulee tieto:
_Nimeke: Ei voida muokata, koska arvo haetaan ominaisuudesta biblio.title
Tekijä: Ei voida muokata, koska arvo haetaan ominaisuudesta biblio.author_
6. Niteet eivät siirry haluttuun käsittelyerään.

**Comment by AnneliO** [comment]
Testailin tätä ja tosiaan tuohon kuvan osoittamaan kohtaan saakka pääsee, mutta sen jälkeen Submit-nappulasta ei tapahdu mitään. Se on lahna. Jos tarkastelee sivun tietoja, niin konsolissa tulee kolme punaista virheilmoitusta ja iso läjä keltaisia.

```
Uncaught TypeError: item.biblio is undefined
    columnApiMapping webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:89
    attributes webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:152
    train_items webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:149
    onSubmit webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:145
    2 webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:39
    callWithErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:284
    callWithAsyncErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:293
    invoker webpack://koha/./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js?:489
[preservation_23.1100000.js line 1168 > eval:89:1](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/js/vue/dist/preservation_23.1100000.js%20line%201168%20%3E%20eval)
[Vue warn]: Unhandled error during execution of native event handler 
  at <TrainsFormAddItems onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <Main> [runtime-core.esm-bundler.js:167:17](webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?)
Uncaught TypeError: item.biblio is undefined
    columnApiMapping webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:89
    attributes webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:152
    train_items webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:149
    onSubmit webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:145
    2 webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:39
    callWithErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:284
    callWithAsyncErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:293
    invoker webpack://koha/./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js?:489
[preservation_23.1100000.js line 1168 > eval:89:1](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/js/vue/dist/preservation_23.1100000.js%20line%201168%20%3E%20eval)
Error in parsing value for '-webkit-text-size-adjust'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:159](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Error in parsing value for 'outline'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:2738](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Error in parsing value for 'outline'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:23399](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. [bootstrap.min_23.1100000.css:7:24347](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. [bootstrap.min_23.1100000.css:7:24446](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Error in parsing value for 'margin-top'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:26035](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Error in parsing value for 'outline'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:32939](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:33283](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:43150](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected color but found '0'.  Error in parsing value for 'border-color'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:59972](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected color but found '0'.  Error in parsing value for 'border-color'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:61849](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Unrecognized at-rule or error parsing at-rule '@-o-keyframes'. [bootstrap.min_23.1100000.css:7:70649](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Unknown property 'zoom'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:74969](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:91855](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:91964](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:93211](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:93264](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:94423](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap.min_23.1100000.css:7:94469](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Unrecognized at-rule or error parsing at-rule '@-ms-viewport'. [bootstrap.min_23.1100000.css:7:99356](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:1590](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:1708](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:2969](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:3087](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:4305](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:4423](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:5638](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:5756](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:6908](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:7026](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:8243](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:8361](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:9708](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:10273](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:10755](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:10900](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:11573](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:12202](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:12347](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:12812](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:13737](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:14413](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:14899](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:15388](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:15876](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:16360](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:16827](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:17302](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:17774](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:18249](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:18723](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:20002](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:20719](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:21202](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:21685](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:22165](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:22648](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:23130](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Source map error: unsupported protocol for sourcemap request webpack://koha/node_modules/vue-select/dist/vue-select.js.map
Resource URL: webpack://koha/./node_modules/vue-select/dist/vue-select.js?
Source Map URL: vue-select.js.map
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [bootstrap-theme.min_23.1100000.css:7:23589](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/bootstrap/bootstrap-theme.min_23.1100000.css)
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. [fontawesome.min_23.1100000.css:6:192](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/fontawesome/css/fontawesome.min_23.1100000.css)
Expected declaration but found ';'.  Skipped to next declaration. [datatables.min_23.1100000.css:13:657](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected declaration but found ';'.  Skipped to next declaration. [datatables.min_23.1100000.css:13:8147](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown property 'zoom'.  Declaration dropped. [datatables.min_23.1100000.css:13:8153](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected declaration but found ';'.  Skipped to next declaration. [datatables.min_23.1100000.css:13:8732](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected declaration but found ';'.  Skipped to next declaration. [datatables.min_23.1100000.css:13:12378](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unrecognized at-rule or error parsing at-rule '@-o-keyframes'. [datatables.min_23.1100000.css:16:68](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unrecognized at-rule or error parsing at-rule '@-ms-keyframes'. [datatables.min_23.1100000.css:16:154](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:1597](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:2304](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:3006](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:3893](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:4587](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:5243](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown property '-moz-column-gap'.  Declaration dropped. [datatables.min_23.1100000.css:16:5774](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. [datatables.min_23.1100000.css:16:6796](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown property '-moz-column-count'.  Declaration dropped. [datatables.min_23.1100000.css:16:7407](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown property '-moz-column-count'.  Declaration dropped. [datatables.min_23.1100000.css:16:7571](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown property '-moz-column-count'.  Declaration dropped. [datatables.min_23.1100000.css:16:7734](https://outi-next.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.css)
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. [_flatpickr.scss:374:8](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/_flatpickr.scss)
Unknown descriptor '700' in @font-face rule.  Skipped to next declaration. [_fonts.scss:12:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/_fonts.scss)
Unknown descriptor 'italic' in @font-face rule.  Skipped to next declaration. [_fonts.scss:13:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/_fonts.scss)
Error in parsing value for 'background-position'.  Declaration dropped. [staff-global.scss:150:8](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Error in parsing value for 'padding'.  Declaration dropped. [staff-global.scss:2267:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Error in parsing value for 'padding'.  Declaration dropped. [staff-global.scss:2274:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-column-gap'.  Declaration dropped. [staff-global.scss:4171:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-columns'.  Declaration dropped. [staff-global.scss:4172:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-column-gap'.  Declaration dropped. [staff-global.scss:4176:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-columns'.  Declaration dropped. [staff-global.scss:4177:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-column-gap'.  Declaration dropped. [staff-global.scss:4181:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown property '-moz-columns'.  Declaration dropped. [staff-global.scss:4182:4](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/css/maps/staff-global.scss)
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. [home.pl:1:5919](https://outi-next.koha-suomi.fi/cgi-bin/koha/preservation/home.pl)
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. [home.pl:1:6516](https://outi-next.koha-suomi.fi/cgi-bin/koha/preservation/home.pl)
[Vue warn]: Unhandled error during execution of native event handler 
  at <TrainsFormAddItems onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy { <target>: {…}, <handler>: {…} }
 > > 
  at <RouterView> 
  at <Main> [runtime-core.esm-bundler.js:167:17](webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?)
Uncaught TypeError: item.biblio is undefined
    columnApiMapping webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:89
    attributes webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:152
    train_items webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:149
    onSubmit webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:145
    2 webpack://koha/./koha-tmpl/intranet-tmpl/prog/js/vue/components/Preservation/TrainsFormAddItems.vue?./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[5].use[0]:39
    callWithErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:284
    callWithAsyncErrorHandling webpack://koha/./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js?:293
    invoker webpack://koha/./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js?:489
[preservation_23.1100000.js line 1168 > eval:89:1](https://outi-next.koha-suomi.fi/intranet-tmpl/prog/js/vue/dist/preservation_23.1100000.js%20line%201168%20%3E%20eval)
Source map error: unsupported protocol for sourcemap request webpack://koha/node_modules/vue-select/dist/vue-select.js.map
Resource URL: webpack://koha/./node_modules/vue-select/dist/vue-select.js?
Source Map URL: vue-select.js.map
```

**Comment by emta001** [comment]
Mielenkiintoista, tää toimii miun testillä. Pitänee tavata tuon ominaisuuden tikettiä/tikettejä, jospa sieltä löytys jokin selitys tälle.

**Comment by emta001** [comment]
Aina vaan jännempää, tää toimii myös Hellen nextillä.

**Comment by emta001** [comment]
Nonnih, eli tämä tilanne syntyy jos käsittelypohjaan on liitetty ominaisuus, joka viittaa johonkin tietokannan tauluun. Sain nyt saman virheen aikaan omalla testilläni.

**Comment by AnneliO** [comment]
Todennäköisesti siis kaikissa jatkossa, koska kyllähän niteistä halutaan näkyviin esim. nimeke ja tekijä. :)

**Comment by emta001** [comment]
> Todennäköisesti siis kaikissa jatkossa, koska kyllähän niteistä halutaan näkyviin esim. nimeke ja tekijä. :)

Tämäpä. Mutta tällä on vaikutusta myös tuohon "submit"-napin lahnailuun, niin jotenkin tää nyt pitäs korjata.

**Comment by emta001** [comment]
Sama ongelma toistuu yhteisön Sandboxissa.

**Comment by AnneliO** [comment]
> Kehtaako @pirliis tai @AnneliO tehdä tästä tiketin yhteisöön, en oo löytänyt sieltä valmista.

Mie voin tehdä.

**Comment by AnneliO** [comment]
Tässäpä se nyt on: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36649

**Comment by emta001** [comment]
> Tässäpä se nyt on: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36649

Kiitos :)

**Comment by AnneliO** [comment]
Tämä korjattiin jo yhteisössä ja on tällä hetkellä Passed QA -tilassa.

Juteltiin Koha-Suomen palaverissa, että seurataan, miten paljon käsittelyerät-toimintoa käytetään ennen kuin tuodaan korjaus myös meille. Jos käyttöä on, niin pohditaan sitten asiaa uudelleen.
